# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

[toolchain]
channel = "stable-2025-04-03"
components = ["clippy", "rustfmt"]
profile = "minimal"
