#!/usr/bin/env sh

# shellcheck shell=sh

# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

# _shellcheck needs to be in $PATH
# https://www.shellcheck.net
#   Mac:
#     brew install shellcheck
#   Linux:
#     sudo apt-get install shellcheck

# shfmt needs to be in $PATH
# https://github.com/mvdan/sh
#   Mac:
#     brew install shfmt
#   Linux:
#     sudo apt-get install shfmt

# yamllint needs to be in $PATH
# https://yamllint.readthedocs.io/en/stable/
#   Mac:
#     brew install yamllint
#   Linux:
#     sudo apt-get install yamllint

# hadolint needs to be in $PATH
# https://github.com/hadolint/hadolint
#   Mac:
#     brew install hadolint
#   Linux:
#     sudo apt-get install hadolint

set -eu

if [ -z "${GIT_REFLOG_ACTION+x}" ]; then
  git stash --quiet --include-untracked --keep-index

  trap 'git stash pop --quiet 2>/dev/null' EXIT INT QUIT TSTP
fi

readonly base_dir="$PWD"

#scripts/shellscript_format_check.sh "${base_dir}"
scripts/shellscript_check.sh "${base_dir}"

# https://yamllint.readthedocs.io/en/stable/quickstart.html#running-yamllint
yamllint --strict "${base_dir}"

# https://github.com/hadolint/hadolint#cli
hadolint --no-color js/nodejs/Dockerfile
hadolint --no-color rust/http/Dockerfile
hadolint --no-color rust/https/Dockerfile

scripts/format_check.sh "${base_dir}"
scripts/lint.sh "${base_dir}"
