# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

version = 1

SPDX-PackageName = "sdavids-docker-healthcheck"
SPDX-PackageSupplier = "Sebastian Davids <sdavids@gmx.de>"
SPDX-PackageDownloadLocation = "https://github.com/sdavids/sdavids-docker-healthcheck"

[[annotations]]
path = "OSSMETADATA"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"
